<!DOCTYPE html><html lang="en" data-ng-app="app"><head><meta charset="utf-8"><title>Yesy Milano | The official website</title><link rel="icon" href="/favicon.ico?v2"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="description" content=" <%= description %> "><meta name="keywords" content=" <%= keywords %> "><link rel="author" href="<%= googleProfile %>"><link rel="publisher" href="<%= googleProfile %>"><meta itemprop="name" content=" <%= title %> "><meta itemprop="description" content=" <%= description %> "><meta itemprop="image" content=" <%= urlWebSite %> <%= image %> "><script type="application/ld+json">{
      "@context" : "http://schema.org",
      "@type": "Organization",
      "url": " <%= urlWebSite %> <%= route %> ",
      "name" : " <%= title %> ",
      "logo": " <%= urlWebSite %> <%= logo %> ",
      "sameAs" : [
        " <%= googleProfile %> ",
        " <%= facebookProfile %> ",
        " <%= twitterProfile %> "
      ]
    }</script><meta property="og:type" content=" <%= og_type %> "><meta property="og:url" content=" <%= urlWebSite %> <%= route %> "><meta property="og:title" content=" <%= title %> "><meta property="og:description" content=" <%= description %> "><meta property="og:image" content=" <%= urlWebSite %> <%= image %> "><meta name="twitter:card" content=" <%= twitterCard %> "><meta name="twitter:site" content=" <%= twitterAccount %> "><meta name="twitter:title" content=" <%= title %> "><meta name="twitter:description" content=" <%= description %> "><meta name="twitter:image" content=" <%= urlWebSite %> <%= image %> "><link rel="stylesheet" href="/css/production.css"><link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css"><link rel="stylesheet" href="/bower_components/simple-line-icons/css/simple-line-icons.css"></head><body ng-controller="AppCtrl"><div class="app" id="app" ng-class="{'app-header-fixed':app.settings.headerFixed, 'app-aside-fixed':app.settings.asideFixed, 'app-aside-folded':app.settings.asideFolded, 'app-aside-dock':app.settings.asideDock, 'container':app.settings.container}"><div ng-include=" '/tpl/blocks/header.html' " class="fade-in app-header navbar-md {{app.settings.navbarCollapseColor}}" ng-class="{'hide': app.settings.hideHeader, 'bg-n': page =='home'}"></div><div ng-include=" '/tpl/blocks/aside.html' " class="app-aside hidden-xs {{app.settings.asideColor}}" ng-class="{'hide': app.settings.hideAside }"></div><div class="app-content" ng-class="{'m-n': app.settings.hideAside, 'h-full': app.settings.hideFooter }"><div class="app-content-body app-content-full fade-in smooth" ng-class="{'app-header-fixed-top': app.settings.hideHeader, 'h-full': app.settings.hideFooter }" ui-view></div></div></div><script src="/js/production.js"></script></body></html>